// AP US Government and Politics content based on College Board Course and Exam Description
export const apgovContent = [
  {
    title: "Foundations of American Democracy",
    period: "Unit 1",
    topic: "The Constitution, Federalism, Democratic Ideals, Republican Government, Limited Government, Systems of Government",
    content: "Unit 1 examines the conceptual and historical foundations of American democracy. Students explore how competing ideas about government influenced the creation and development of the U.S. Constitution. Key democratic principles including popular sovereignty, republicanism, limited government, and federalism are analyzed in both theory and practice. The Constitution's provisions for checks and balances and separation of powers are examined as mechanisms to prevent tyranny and ensure accountability. Federalism—the division of power between national and state governments—is analyzed through constitutional provisions, Supreme Court decisions, and ongoing tensions. The unit traces how interpretations of federalism have evolved through American history, from dual federalism to cooperative federalism and new federalism. Students evaluate the ongoing debates about the proper balance of power in the American system, considering how democratic ideals sometimes conflict with practical governance challenges."
  },
  {
    title: "Civil Liberties and Civil Rights",
    period: "Unit 2",
    topic: "The Bill of Rights, Due Process, Equal Protection, Selective Incorporation, Freedom of Religion, Speech, Press, Assembly, Petition, Right to Bear Arms, Right to Privacy",
    content: "Unit 2 explores the Constitutional protections for individual liberties and the evolution of civil rights in America. Civil liberties—protections against government actions—are examined through First Amendment freedoms (religion, speech, press, assembly, petition), Second Amendment rights, and criminal procedure protections. The selective incorporation process, applying Bill of Rights protections to state governments through the Fourteenth Amendment, is analyzed through key Supreme Court cases. Civil rights—protection from discrimination—are traced through the struggle for racial equality from slavery through Reconstruction, Jim Crow, and the Civil Rights Movement. The equal protection clause and its application to combat discrimination based on race, gender, and other characteristics are examined through landmark cases and legislation. Students analyze how social movements have expanded civil rights protections over time, and evaluate ongoing debates about the scope and limits of rights and liberties in contemporary society."
  },
  {
    title: "American Political Ideologies and Beliefs",
    period: "Unit 3",
    topic: "Political Socialization, Political Ideologies, Public Opinion, Political Culture, Media Influence",
    content: "Unit 3 examines the formation and characteristics of American political beliefs and their influence on the political system. American political culture is analyzed through core values including liberty, equality, democracy, individualism, the rule of law, and civic duty. Political socialization processes—how individuals develop political attitudes through family, education, peers, media, and other influences—are examined. Students explore the spectrum of political ideologies from liberal to conservative and how they manifest in American politics. Public opinion measurement through polling and surveys is analyzed, including methodologies and limitations. Factors influencing public opinion include demographics, political culture, and momentary events. The unit examines how political beliefs drive policy preferences on economic and social issues. Students evaluate the extent to which political ideology correlates with party identification and how party realignment and dealignment have occurred over time."
  },
  {
    title: "Political Participation",
    period: "Unit 4",
    topic: "Voting, Elections, Political Parties, Interest Groups, PACs, Social Movements, Media",
    content: "Unit 4 analyzes how Americans participate in political processes. Voting rights expansion is traced through constitutional amendments and legislation removing barriers based on race, gender, and age. Voter turnout trends and their demographics are examined, along with factors affecting participation including registration requirements, voter ID laws, and socioeconomic factors. The electoral process is analyzed, including the electoral college system, primary types, general elections, and campaign finance regulations. Political parties' functions, organization, and evolution are studied, with attention to the two-party system's development and third parties' challenges. Interest groups and political action committees (PACs) are examined as mechanisms for influencing policy through lobbying, campaign contributions, and grassroots mobilization. Media's role in politics—including traditional and social media—is analyzed for its agenda-setting, gatekeeping, and framing functions. Students evaluate how technology has transformed political participation and communication in contemporary democracy."
  },
  {
    title: "Interactions Among Branches of Government",
    period: "Unit 5",
    topic: "Congress, Presidency, Judiciary, Checks and Balances, Separation of Powers, Bureaucracy, Budget Process",
    content: "Unit 5 examines how the three branches of government interact in policymaking and governance. Congress's structure, powers, and functions are analyzed, including legislation processes, representation, oversight, and approval powers. The presidency's formal and informal powers are examined, along with how presidential power has expanded throughout American history. The federal judiciary's structure and its power of judicial review are analyzed, including how the Supreme Court's composition affects constitutional interpretation. Students explore how the separation of powers and checks and balances create both conflict and cooperation among branches. The federal bureaucracy's role in implementing policy is examined, including its structures, regulations, and relationships with other branches. The federal budget process illustrates interbranch relationships through authorization, appropriation, and oversight functions. Students evaluate how policy emerges from the complex interactions among branches, analyzing examples of when the system produces gridlock versus effective governance."
  },
  {
    title: "Legal Analysis and Constitutional Interpretation",
    period: "Exam skills",
    topic: "Exam skills",
    content: "This section develops skills in analyzing and interpreting constitutional provisions, Supreme Court cases, and legal principles. Students practice identifying constitutional clauses relevant to specific political issues and conflicts between government branches. The section covers different approaches to constitutional interpretation, including originalism, living constitution, strict vs. broad construction, and textualism. Students learn to analyze Supreme Court majority opinions, concurrences, and dissents to identify legal reasoning and constitutional principles. The section emphasizes understanding stare decisis (precedent) and how cases build upon or overturn previous decisions. Students practice applying precedents to new factual situations, an essential skill for the Court comparison FRQ on the exam. The section also develops skills in evaluating the constitutional basis for governmental actions, including presidential directives, congressional legislation, and agency regulations. Students learn to construct evidence-based arguments about constitutional questions using appropriate legal terminology, applicable constitutional provisions, and relevant Supreme Court precedents."
  },
  {
    title: "Data Analysis and Political Research",
    period: "Exam skills",
    topic: "Exam skills",
    content: "This section focuses on analyzing and interpreting political data in various formats. Students practice interpreting quantitative data including voter demographics, public opinion polls, electoral results, and congressional voting patterns. The section emphasizes identifying trends, correlations, and patterns in political data while recognizing the limitations of data and avoiding unsupported conclusions. Students learn to evaluate polling methodology, including sample size, margin of error, question wording, and potential biases. The section covers analyzing visual representations of data such as charts, graphs, and maps commonly used in political analysis. Students practice comparing data sources to identify consistencies and contradictions in political research. The section also develops skills in analyzing qualitative sources like political speeches, party platforms, and interest group position statements to identify ideological perspectives and political strategies. Students learn to construct evidence-based arguments using appropriate data and examples, a critical skill for the quantitative analysis FRQ on the exam."
  },
  {
    title: "Policy Analysis",
    period: "Exam skills",
    topic: "Exam skills",
    content: "This section develops skills in analyzing domestic and foreign policy issues and processes. Students practice identifying policy problems, stakeholders, and alternative solutions across domains including economic, social, environmental, and security policy. The section emphasizes understanding the policy process from agenda-setting through implementation and evaluation. Students learn to analyze how different political actors—including Congress, the President, courts, bureaucracy, interest groups, and media—influence policy outcomes. The section covers evaluating policy proposals using criteria such as constitutionality, political feasibility, economic efficiency, and effectiveness. Students practice identifying intended and unintended consequences of policies, including how policies may affect different population groups. The section also develops skills in comparing competing policy approaches to addressing the same problem, drawing on different ideological frameworks. Students learn to construct evidence-based arguments about policy choices, incorporating relevant political principles, institutional capabilities, constraints, and trade-offs—skills essential for the argument essay FRQ on the exam."
  }
];