// AP Psychology content based on College Board Course and Exam Description
// Comprehensive coverage of all 7 units in AP Psychology

export const appsychContent = [
    {
        title: "Biological Bases of Behavior",
        period: "Unit 1",
        unit: "Unit 1", 
        topic: "Brain anatomy, neurotransmitters, nervous system, genetics and behavior",
        content: "The biological approach to psychology examines how biological factors influence behavior and mental processes. The nervous system consists of the central nervous system (brain and spinal cord) and peripheral nervous system (somatic and autonomic divisions). The autonomic nervous system includes sympathetic (fight-or-flight) and parasympathetic (rest-and-digest) divisions. Neurons are the basic building blocks of the nervous system, consisting of cell body, dendrites, and axon. Action potentials are electrical impulses that travel down axons. Neurotransmitters are chemical messengers that cross synapses between neurons. Key neurotransmitters include acetylcholine (muscle movement, memory), dopamine (reward, movement), serotonin (mood, sleep), norepinephrine (alertness, arousal), GABA (inhibitory, calming), and glutamate (excitatory, learning). Brain structures and functions: brainstem controls vital functions, cerebellum coordinates movement and balance, limbic system (including hippocampus for memory and amygdala for emotion) processes emotions and memory, cerebral cortex handles higher-order thinking. The cortex includes frontal lobe (executive functions, motor control), parietal lobe (sensory processing), temporal lobe (auditory processing, language), and occipital lobe (visual processing). Genetics influence behavior through heritability studies, twin studies, and adoption studies. Brain plasticity allows the nervous system to adapt and reorganize throughout life."
    },
    {
        title: "Sensation and Perception",
        period: "Unit 2",
        unit: "Unit 2",
        topic: "Sensory processes, perceptual organization, visual and auditory processing",
        content: "Sensation is the process of detecting physical stimuli from the environment, while perception is the interpretation and organization of sensory information. Thresholds determine our sensitivity to stimuli: absolute threshold is the minimum stimulus intensity we can detect 50% of the time, difference threshold (just noticeable difference) is the smallest change in stimulus intensity we can detect. Weber's Law states that the just noticeable difference is proportional to the original stimulus intensity. Signal detection theory explains how we detect signals in the presence of noise, influenced by sensitivity and response bias. Sensory adaptation occurs when sensitivity decreases with constant exposure to a stimulus. Visual processing begins in the eye: light enters through the cornea, passes through the pupil (controlled by the iris), is focused by the lens onto the retina. The retina contains photoreceptors - rods (sensitive to light, used for night vision) and cones (sensitive to color, concentrated in the fovea for detailed vision). Visual information travels via the optic nerve to the thalamus, then to the visual cortex. Color vision theories include trichromatic theory (three types of cones) and opponent-process theory (color pairs that cannot be perceived simultaneously). Auditory processing: sound waves are collected by the outer ear, transmitted through the middle ear (eardrum, ossicles), and converted to neural signals in the inner ear (cochlea). Hair cells in the cochlea detect different frequencies. Pitch perception theories include place theory (different locations on cochlea detect different frequencies) and frequency theory (firing rate corresponds to frequency). Other senses include touch (pressure, temperature, pain), taste (five basic tastes), smell (olfactory processing), and proprioception (body position). Perceptual organization follows Gestalt principles: figure-ground, proximity, similarity, closure, continuity. Depth perception uses monocular cues (linear perspective, relative size, interposition) and binocular cues (retinal disparity, convergence). Perceptual constancies maintain stable perception despite changing sensory input."
    },
    {
        title: "Learning",
        period: "Unit 3", 
        unit: "Unit 3",
        topic: "Classical conditioning, operant conditioning, observational learning, cognitive learning",
        content: "Learning is a relatively permanent change in behavior due to experience. Classical conditioning, discovered by Ivan Pavlov, involves learning through association. Key components include unconditioned stimulus (UCS) that naturally produces an unconditioned response (UCR), conditioned stimulus (CS) that becomes associated with the UCS, and conditioned response (CR) that results from the CS. Acquisition occurs when the CS-UCS association is learned. Extinction happens when the CS is presented without the UCS, causing the CR to weaken. Spontaneous recovery is the reappearance of the CR after extinction. Stimulus generalization occurs when similar stimuli produce the CR, while stimulus discrimination involves responding only to the specific CS. Higher-order conditioning involves using an established CS as a UCS for new learning. Classical conditioning applications include phobias, taste aversion, and emotional responses. Operant conditioning, developed by B.F. Skinner, involves learning through consequences. Reinforcement increases behavior probability: positive reinforcement adds something desirable, negative reinforcement removes something undesirable. Punishment decreases behavior probability: positive punishment adds something undesirable, negative punishment removes something desirable. Reinforcement schedules affect learning: continuous reinforcement strengthens learning quickly but leads to rapid extinction, partial reinforcement creates resistance to extinction. Partial schedules include fixed-ratio (reinforcement after set number of responses), variable-ratio (reinforcement after varying number of responses), fixed-interval (reinforcement after set time period), and variable-interval (reinforcement after varying time periods). Shaping involves reinforcing successive approximations toward a target behavior. Observational learning, studied by Albert Bandura, involves learning by watching others. The Bobo doll experiment demonstrated that children imitate aggressive behaviors they observe. Observational learning requires attention, retention, reproduction, and motivation. Cognitive learning involves mental processes like insight learning (sudden understanding) and latent learning (learning without immediate performance)."
    },
    {
        title: "Cognitive Psychology",
        period: "Unit 4",
        unit: "Unit 4", 
        topic: "Memory, thinking, problem solving, language, intelligence",
        content: "Memory involves three processes: encoding (getting information into memory), storage (maintaining information), and retrieval (getting information out of memory). The multi-store model proposes three memory systems: sensory memory (brief storage of sensory information), short-term memory (limited capacity ~7±2 items, limited duration ~30 seconds), and long-term memory (unlimited capacity and duration). Working memory expands on short-term memory with active processing components: phonological loop (auditory information), visuospatial sketchpad (visual information), central executive (attention control), and episodic buffer (integrates information). Long-term memory types include explicit/declarative memory (conscious recollection) and implicit/non-declarative memory (unconscious influences). Explicit memory includes episodic memory (personal experiences) and semantic memory (general knowledge). Implicit memory includes procedural memory (skills), priming, and conditioning. Encoding strategies include elaborative rehearsal (meaningful processing), visual imagery, and organization. The levels of processing theory suggests deeper processing leads to better memory. Retrieval can be improved through retrieval cues, context-dependent learning, and state-dependent learning. Forgetting occurs through decay, interference (proactive and retroactive), and motivated forgetting. Memory reconstruction involves filling gaps with expectations and schemas. Thinking involves mental representations and cognitive processes. Concepts are mental categories that organize knowledge. Problem-solving strategies include algorithms (systematic procedures) and heuristics (mental shortcuts). Common heuristics include representativeness heuristic, availability heuristic, and anchoring bias. Cognitive biases affect decision-making, including confirmation bias, overconfidence, and framing effects. Language development follows predictable stages: babbling, one-word stage, two-word stage, telegraphic speech. Language acquisition theories include behaviorist (imitation and reinforcement), nativist (innate language acquisition device), and social interactionist (social interaction drives learning). Intelligence is the ability to learn, solve problems, and adapt to the environment. Theories include Spearman's g-factor, Gardner's multiple intelligences, and Sternberg's triarchic theory. Intelligence testing began with Binet and Simon, leading to the concept of IQ (mental age/chronological age × 100). Modern tests like the WAIS measure various cognitive abilities."
    },
    {
        title: "Developmental Psychology", 
        period: "Unit 5",
        unit: "Unit 5",
        topic: "Physical, cognitive, and social development across the lifespan",
        content: "Developmental psychology studies changes across the lifespan in physical, cognitive, and social domains. Nature vs. nurture debates whether genetics or environment primarily influences development. Critical periods are specific times when development must occur, while sensitive periods are optimal times for development. Prenatal development includes germinal stage (0-2 weeks), embryonic stage (2-8 weeks), and fetal stage (8 weeks-birth). Teratogens are environmental factors that can harm development. Physical development in infancy includes reflexes (rooting, sucking, grasping), motor milestones (sitting, crawling, walking), and brain development (synaptic pruning, myelination). Cognitive development theories: Piaget's stages include sensorimotor (0-2 years, object permanence), preoperational (2-7 years, symbolic thinking, egocentrism), concrete operational (7-11 years, logical thinking about concrete objects), and formal operational (11+ years, abstract thinking). Key concepts include schemas, assimilation, accommodation, and equilibration. Vygotsky emphasized social interaction and the zone of proximal development. Information processing approaches focus on changes in attention, memory, and processing speed. Social development includes attachment theory by Bowlby and Ainsworth. Attachment styles include secure, anxious-ambivalent, avoidant, and disorganized. Harlow's monkey experiments demonstrated the importance of contact comfort over feeding for attachment. Parenting styles by Baumrind include authoritative (high warmth, high control), authoritarian (low warmth, high control), permissive (high warmth, low control), and neglectful (low warmth, low control). Erikson's psychosocial stages describe conflicts throughout life: trust vs. mistrust (infancy), autonomy vs. shame (early childhood), initiative vs. guilt (preschool), industry vs. inferiority (school age), identity vs. role confusion (adolescence), intimacy vs. isolation (young adulthood), generativity vs. stagnation (middle age), and integrity vs. despair (late life). Adolescence involves puberty, identity formation, and increased risk-taking due to brain development patterns. Moral development theories include Kohlberg's stages: preconventional (consequences), conventional (social approval), and postconventional (universal principles). Adult development includes physical changes, cognitive changes, and social role transitions. Aging involves both decline (processing speed, some memory) and stability (crystallized intelligence, personality)."
    },
    {
        title: "Personality",
        period: "Unit 6",
        unit: "Unit 6",
        topic: "Personality theories, assessment, and individual differences", 
        content: "Personality refers to consistent patterns of thinking, feeling, and behaving across situations and time. Psychodynamic theories, originated by Freud, emphasize unconscious forces and early childhood experiences. Freud's structural model includes id (pleasure principle, unconscious desires), ego (reality principle, mediates between id and superego), and superego (moral principle, internalized standards). Freud's psychosexual stages include oral (0-1 year), anal (1-3 years), phallic (3-6 years, Oedipus/Electra complex), latency (6-puberty), and genital (puberty+). Defense mechanisms protect the ego from anxiety: repression, denial, projection, displacement, sublimation, reaction formation, and rationalization. Neo-Freudians like Jung (collective unconscious, archetypes), Adler (individual psychology, inferiority complex), and Horney (social and cultural factors) modified Freudian theory. Humanistic theories emphasize personal growth and self-actualization. Rogers proposed that personality develops through the interaction between the self-concept and experiences. Conditions of worth can create incongruence between the ideal self and real self. Maslow's hierarchy of needs includes physiological, safety, love/belonging, esteem, and self-actualization needs. Trait theories focus on identifying and measuring personality dimensions. Allport distinguished between cardinal traits (dominant), central traits (characteristic), and secondary traits (situational). Cattell used factor analysis to identify 16 personality factors. The Big Five model includes openness to experience, conscientiousness, extraversion, agreeableness, and neuroticism (OCEAN). These traits are relatively stable across time and situations, have genetic components, and predict important life outcomes. Social-cognitive theories emphasize the interaction between behavior, cognitive factors, and environment. Bandura's reciprocal determinism describes how these three factors influence each other. Self-efficacy is the belief in one's ability to succeed in specific situations. Rotter's concept of locus of control describes whether people believe outcomes are controlled by internal factors (themselves) or external factors (luck, others). Personality assessment methods include objective tests (MMPI, NEO-PI-R), projective tests (Rorschach inkblot, TAT), and behavioral observation. Reliability refers to consistency of measurement, while validity refers to whether a test measures what it claims to measure."
    },
    {
        title: "Abnormal Behavior",
        period: "Unit 7",
        unit: "Unit 7", 
        topic: "Psychological disorders, diagnosis, etiology, and treatment approaches",
        content: "Abnormal behavior is defined by deviation from statistical norms, cultural norms, personal distress, and maladaptive behavior. The medical model views psychological disorders as diseases with biological causes. The DSM-5 (Diagnostic and Statistical Manual) provides criteria for diagnosing mental disorders using a categorical approach. The biopsychosocial model considers biological, psychological, and social factors in understanding disorders. Anxiety disorders involve excessive fear and anxiety. Generalized anxiety disorder involves persistent worry about multiple areas. Panic disorder includes recurrent panic attacks and fear of future attacks. Phobias are persistent, irrational fears of specific objects or situations. Social anxiety disorder involves fear of social or performance situations. Obsessive-compulsive disorder includes obsessions (intrusive thoughts) and compulsions (repetitive behaviors). Post-traumatic stress disorder can develop after exposure to traumatic events. Mood disorders affect emotional states. Major depressive disorder involves persistent sadness, loss of interest, and other symptoms for at least two weeks. Bipolar disorder involves alternating episodes of depression and mania. Seasonal affective disorder is depression related to reduced sunlight exposure. Explanations for depression include biological factors (neurotransmitter imbalances, genetics), psychological factors (negative thinking patterns, learned helplessness), and social factors (stressful life events, social support). Schizophrenia is a severe disorder involving delusions, hallucinations, disorganized thinking, and abnormal motor behavior. Positive symptoms include delusions and hallucinations, while negative symptoms include reduced emotional expression and motivation. The dopamine hypothesis suggests that schizophrenia involves excess dopamine activity. Risk factors include genetics, prenatal factors, and environmental stressors. Dissociative disorders involve disruptions in consciousness, memory, or identity. Dissociative identity disorder (formerly multiple personality disorder) involves two or more distinct personality states. Personality disorders are enduring patterns of behavior that deviate from cultural expectations. Antisocial personality disorder involves disregard for others' rights. Borderline personality disorder involves instability in relationships and self-image. Treatment approaches include biological treatments (medications, ECT, psychosurgery), psychodynamic therapy (insight-oriented, transference), humanistic therapy (client-centered, gestalt), behavioral therapy (systematic desensitization, exposure therapy), cognitive therapy (identifying and changing negative thought patterns), and cognitive-behavioral therapy (combining cognitive and behavioral techniques). Effectiveness varies by disorder and individual factors. Ethical considerations include informed consent, confidentiality, and cultural sensitivity."
    }
];